#pragma once

// PLAYER MOVEMENT AND SIZE
#define PLAYERSPEED 1 // SPEED OF PLAYER, ONLY INT ACCEPTED
#define Climb 1 // SPEED OF CLIMBING, ONLY INT ACCEPTED
#define Gravity 1 // SPEED OF FALLING, ONLY INT ACCEPTED
#define CHARACTER 1.5 // MAX 1.5
#define TIME 20 // TIME TO STOP PLAYER AFTER KEY RELEASED
#define GROW 8 // PLAYER POSITION AFTER GAME ENDING
#define PLAYER_GROW 1.2 // PLAYER SIZE AFTER GAME ENDING

//POSITION OF MENU
#define MENU 16

//BARRELS PARAMETERS
#define BARREL_SPAWN 70 // LOWER - > BARRELS SPAWN FASTER, ONLY INT ACCEPTED
#define BARRELSPEED 5 // SPEED OF BARRELS, ONLY INT ACCEPTED
#define BARRELSIZE 32

//GAME PARAMETERS:
#define SCREEN_WIDTH 800
#define SCREEN_HEIGHT 640

#define SIZE 32 // SIZE OF GAME OBJECTS

//NUMBER OF PLATFORMS AND LADDERS
#define LADDERS 5
#define PLATFORMS 6

const int GRAVITY = 4 * Gravity;
const int CLIMB = 4 * Climb;